### ISSUE TITLE
Double Scoring

### ISSUE THREAD

**Issue by DinkyKing** [DinkyKing/BasketBallVR#11]
If the ball rolls around the hoop there is multiple scoring, have to turn off the scoring collider once you have scored and then reactivate it on the next throw.

**Comment by llamapixel** [comment]
Yes, once you have determined that a ball has passed a "point of no return",
you are sic " good as gold" to say a referee claimed it as his own validation.

Disable the boolean on the first detection object on first pass.

**Comment by centralccoastgamedev** [comment]
change state of boolean on the detect score object.
