### ISSUE TITLE
Game is starting to lag/stutter

### ISSUE THREAD

**Issue by DinkyKing** [DinkyKing/BasketBallVR#13]
Will check the built version.
Will Trim and Clean up the game a bit.

**Comment by DinkyKing** [comment]
The problem is with the cheerleaders, disabling them stops the stutter.

**Comment by llamapixel** [comment]
Ok perhaps they have too many particles?

**Comment by llamapixel** [comment]
I turn off the camera system and my fps goes back up.

**Comment by llamapixel** [comment]
Extra cameras are not only expensive in normal games but double again in VR.

**Comment by llamapixel** [comment]
![screen shot 2017-06-15 at 11 43 06 pm](https://user-images.githubusercontent.com/6301423/27184114-6cde3d36-5224-11e7-97a3-2137589a19d0.png)
![Uploading Screen Shot 2017-06-15 at 11.42.58 PM.png…]()

Compare the two

**Comment by DinkyKing** [comment]
No more stutter, and good frames.
