### ISSUE TITLE
Joshs sound issue

### ISSUE THREAD

**Issue by llamapixel** [DinkyKing/BasketBallVR#5]
Store sounds into array to play randomly
Make an array of sounds

**Comment by llamapixel** [comment]
Use something less complex until we make a script that dynamically gets the files from a folder and stores them into an array.



`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RandomSound : MonoBehaviour {

	//	Sets the seed for the random number generator.
	//	The random number generator is not truly random but produces numbers in a preset sequence 
	//	(the values in the sequence "jump" around the range in such a way that they appear random for most purposes).
	// Random.seed = 10;  DEPRECIATED
	Random.InitState (5);// Is it really seeding?

	int RandomSoundCase = Random.value;

	public AudioClip Sound_001;
	public AudioClip Sound_002;
	public AudioClip Sound_003;
	public AudioClip Sound_004;
	public AudioClip Sound_005;


	void Update () {


		if (Input.GetKeyDown("space")){

			RandomSoundCase = Random.value;

			switch (RandomSoundCase)
			{

				case 5:
					GetComponent<AudioSource>().PlayOneShot(Sound_005);
					break;
				case 4:
					GetComponent<AudioSource>().PlayOneShot(Sound_004);
					break;
				case 3:
					GetComponent<AudioSource>().PlayOneShot(Sound_003);
					break;
				case 2:
					GetComponent<AudioSource>().PlayOneShot(Sound_002);
					break;
				case 1:
					GetComponent<AudioSource>().PlayOneShot(Sound_001);
					break;
				
				default:
					// derp
					break;
			}

		}

	}
		
}

`

**Comment by llamapixel** [comment]
fixed code remarks in issue tracker with 3 ```

**Comment by DinkyKing** [comment]
Audio is a little choppy but now its randomised

**Comment by llamapixel** [comment]
We need to consider that next wave, perhaps its something to do with the channels being played at once.
