### ISSUE TITLE
Hoop Sound effect needs different Collider

### ISSUE THREAD

**Issue by DinkyKing** [DinkyKing/BasketBallVR#6]
Need a hoop sound effect

**Comment by llamapixel** [comment]
What about something like this?

https://www.youtube.com/watch?v=QCPtBNuPzHw

**Comment by llamapixel** [comment]
Unity5 might have some sound issues but I am sure we can solve anything.
https://forum.unity3d.com/threads/serious-audio-problems-with-unity-5.308460/

**Comment by DinkyKing** [comment]
All working, added a capsule collider.

**Comment by llamapixel** [comment]
don't forget to update this projects kanban area with changes.
