### ISSUE TITLE
Dribble

### ISSUE THREAD

**Issue by DinkyKing** [DinkyKing/BasketBallVR#8]
Hitting the ball without grabbing it should make it bounce,
The ball has to add velocity from the power of the paddle.

**Comment by llamapixel** [comment]
If you have more information about the problem or a key sentence problem you can convey a better issue.

I am thinking however you are looking for something like this...


An invisible collision cube that is on your virtual hand that is deactivated when the grab feature is activated.

A Finite state machine or Case Select State

Dribbling / Grabbing.

The invisible collision cube is scaled like a flat hand paddle.
The invisible collision cube has a hand like physics material. ( Skin? )

**Comment by llamapixel** [comment]
If you want to toggle something instead of states.


``
	if(Input.GetKeyDown(KeyCode.T))
		{
			myThing = !myThing ;
			myCurrentValue = myThing ? 0 : 1 ;
		}
``

**Comment by DinkyKing** [comment]
Might need to chat in person to get this one down. But ill give it a try.

**Comment by llamapixel** [comment]
![screen shot 2017-06-08 at 5 00 19 pm](https://user-images.githubusercontent.com/6301423/26916054-0a44fe66-4c6c-11e7-910b-bde7d5e2a350.png)

I have to fake the dribble but the screen shot should show you how I am achieving it.

**Comment by llamapixel** [comment]
The new idea was to have a collider on a hing like object attached to the hand.
The collider will always face parallel to the ground so the dribble ball angle is always going to constant
