### ISSUE TITLE
BasketBallHoop Collider, You can score by throwing for beneath.

### ISSUE THREAD

**Issue by DinkyKing** [DinkyKing/BasketBallVR#9]
The basketballhoop collider isTrigger, detects the collision when the ball hits from under the hoop.
Is there anyway you can check if the ball hits from the top only?
Or is there a way to check if the ball is going up or down?

**Comment by llamapixel** [comment]
You could make two cylinders that are collision detections systems of your preference around the hoop.

If the ball hits the magenta first which makes it true and then hits the top green one you have a false condition.
If the ball hits the green one first and the magenta is false, you have a true and valid dunk.


top - green
hoop - red
bottom - magenta

The cylinders determine what was hit first and therefore will determine a false direction through the hoop.

![screen shot 2017-06-08 at 9 07 50 pm](https://user-images.githubusercontent.com/6301423/26925865-bb8becf8-4c8e-11e7-9645-a981e673a0a3.png)


Alternatively ...
You could even attempt to determine if the ball is travelling in an intended direction ( Think minus Y ) but you will have to be careful with detection and if the ball rolls into the hoop at a very slow gradient.

**Comment by DinkyKing** [comment]
Cant believe I didnt think of that, must have been overthinking everything. 
All good now, and also now you can only score once a throw
